language: node_js
node_js:
  - "10"
  - "9"
  - "8"
  - "7"
  - "6"
  - "5"
  - "4"

script: yarn test && yarn test-demo

jobs:
  include:
    - stage: Lint
      node_js: "6"
      script: yarn lint
