language: node_js
node_js:
  - "7"
  - "6"
  - "5"
  - "4"

jobs:
  include:
    - stage: Lint
      node_js: "6"
      script: yarn lint
    - stage: Test
      script: yarn test
    - stage: Test demo
      script: yarn test-demo
